CREATE TABLE IF NOT EXISTS booking_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  requester_user_id BIGINT UNSIGNED NULL,
  requester_profile_id BIGINT UNSIGNED NULL,
  requester_type ENUM('guest','user','artist','venue') NOT NULL DEFAULT 'guest',
  contact_name VARCHAR(120) NULL,
  contact_email VARCHAR(190) NULL,
  contact_phone VARCHAR(64) NULL,
  event_title VARCHAR(190) NULL,
  event_date DATE NULL,
  start_time TIME NULL,
  end_time TIME NULL,
  venue_name VARCHAR(190) NULL,
  venue_address VARCHAR(255) NULL,
  city VARCHAR(120) NULL,
  state VARCHAR(64) NULL,
  zip CHAR(5) NULL,
  budget_min DECIMAL(10,2) NULL,
  budget_max DECIMAL(10,2) NULL,
  notes TEXT NULL,
  auto_fallback TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('draft','open','fulfilled','cancelled') NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_requester_user (requester_user_id),
  KEY idx_requester_profile (requester_profile_id),
  KEY idx_event_date (event_date),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS booking_invites (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_id BIGINT UNSIGNED NOT NULL,
  target_profile_id BIGINT UNSIGNED NOT NULL,
  target_type ENUM('artist','venue') NOT NULL,
  priority INT NOT NULL DEFAULT 1,
  status ENUM('pending','accepted','declined','expired','cancelled') NOT NULL DEFAULT 'pending',
  sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at DATETIME NULL,
  message TEXT NULL,
  PRIMARY KEY (id),
  KEY idx_request (request_id),
  KEY idx_target (target_profile_id, status),
  UNIQUE KEY uniq_request_target (request_id, target_profile_id),
  CONSTRAINT fk_invite_request FOREIGN KEY (request_id) REFERENCES booking_requests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
